### ISSUE TITLE
when use_chars is True ，a problem arose？

### ISSUE THREAD

**Issue by PrivateThink** [soujanyaporia/aspect-extraction#5]
Traceback (most recent call last):
  File "/home/wsy/python36_cuda9/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2349, in get_attr
    c_api.TF_OperationGetAttrValueProto(self._c_op, name, buf)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'ExtractImagePatches' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wsy/python36_cuda9/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 391, in _MaybeCompile
    xla_compile = op.get_attr("_XlaCompile")
  File "/home/wsy/python36_cuda9/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2353, in get_attr
    raise ValueError(str(e))
ValueError: Operation 'ExtractImagePatches' has no attr named '_XlaCompile'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 26, in <module>
    main()
  File "train.py", line 12, in main
    model.build()
  File "/home/wsy/qa/aspect_extraction-master/model/aspect_model.py", line 409, in build
    self.config.clip)
  File "/home/wsy/qa/aspect_extraction-master/model/base_model.py", line 54, in add_train_op
    grads, vs= zip(*optimizer.compute_gradients(loss))
  File "/home/wsy/python36_cuda9/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 511, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/home/wsy/python36_cuda9/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 532, in gradients
    gate_gradients, aggregation_method, stop_gradients)
  File "/home/wsy/python36_cuda9/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 701, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "/home/wsy/python36_cuda9/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 396, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/home/wsy/python36_cuda9/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 701, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/home/wsy/python36_cuda9/lib/python3.6/site-packages/tensorflow/python/ops/array_grad.py", line 749, in _ExtractImagePatchesGrad
    rows_out = int(ceil(rows_in / stride_r))
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

could you help me？

**Comment by soujanyaporia** [comment]
You can not use character embedding this way because the task is to tag each word. Typically, you use character embeddings for sentence classification. Alternatively, you could concat word embeddings with character embeddings and then apply this network on that modified word embeddings.

**Comment by PrivateThink** [comment]
very thanks
